### ISSUE TITLE
Chat is broken in Safari on iPad OS Beta

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/emberclear#103]
see, @tylerharrison1188 

TODO:
 - find a way to run tests in mobile systems

**Comment by tylerharrison1188** [comment]
@NullVoxPopuli looks like the hamburger button/slide out is broken on iOS and iPad OS

**Comment by NullVoxPopuli** [comment]
Got the issue: 
![image](https://user-images.githubusercontent.com/199018/64910690-2fd83a00-d6e7-11e9-978e-f651b4b28405.png)

Looks like Safari doesn't support native web animations

**Comment by NullVoxPopuli** [comment]
I'll need to come up with a way to polyfill that for safari users

**Comment by NullVoxPopuli** [comment]
Works on Chrome on the iPad though

**Comment by NullVoxPopuli** [comment]
it looks like you can still open the sidebar on Safari if you drag it with your finger. It's the tweening isn't supported on safari

**Comment by NullVoxPopuli** [comment]
Though, Chrome on iOS has other issues, such as layout, 

and iOS in general has some scroll differences that need to be figured out -- like preventing overscroll

**Comment by NullVoxPopuli** [comment]
I made a whole project dedicated to iOS things https://github.com/NullVoxPopuli/emberclear/projects/7?add_cards_query=is%3Aopen

**Comment by NullVoxPopuli** [comment]
@tylerharrison1188 closing this for now.

The slide out menu is fixed in safari -- for other safari-related issues, we'll want to open more specific tickets
