### ISSUE TITLE
Investigate Channels

### ISSUE THREAD

**Issue by CelticMajora** [NullVoxPopuli/emberclear#142]
Estimated Time: ???

Potential Usage Ideas:

- Anybody online in the channel receives message

Questions to answer:

- Should they be torn down when the founder leaves, when the second to last person leaves, or when the last person leaves?

**Comment by NullVoxPopuli** [comment]
Related Issue: https://github.com/NullVoxPopuli/emberclear/issues/77
Blocked By: https://github.com/NullVoxPopuli/emberclear/pull/110

**Comment by NullVoxPopuli** [comment]
closing, cause this is tracked in #77
