### ISSUE TITLE
WebSockets and Encryption should all be in Web Workers (threads)

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/emberclear#148]
Web Workers are how the web works with threads.

Websockets and encryption are not vital to the UI / Main thread, so they should be abstracted.

This means, however, than we need a concurrency handling library outside of ember, as ember-concurrency relies on Emberisms, which would not be present in these web workers

/cc @machty ;)

**Comment by machty** [comment]
Vanilla e-c core in webworkers would be pretty cool huh
