### ISSUE TITLE
'Newer messages' floater does not immediately disappear after manually scrolling down

### ISSUE THREAD

**Issue by amgassert** [NullVoxPopuli/emberclear#154]
## Expected Behavior
Floater disappears after using the scroll bar to move to the bottom of the chat container

## Actual Behavior
Floater lingers for about ten seconds, covering the most recent message

## Steps to Reproduce
1. Send messages until the chat container overflows
2. Scroll up to trigger the 'newer messages' floater
3. Manually scroll back to the bottom instead of clicking the floater
4. Observe that the floater does not immediately disappear

## Screenshots
[Example](https://imgur.com/ciM48Sd)

**Comment by NullVoxPopuli** [comment]
Fixed
