### ISSUE TITLE
Error in chat: An error occurred in the socket connection!

### ISSUE THREAD

**Issue by Phate6660** [NullVoxPopuli/emberclear#19]
So, I just added a friend as a contact. Upon the contact being added an error appeared saying the error message I put in the title. I have attached a screenshot to show you. I can not send messages either. Is their anything specific in the browser that needs to be enabled? I use [this hardened user.js for Firefox](https://github.com/pyllyukko/user.js/), and I also use [DNSCrypt](https://github.com/jedisct1/dnscrypt-proxy).
Note: I have whitelisted this site from [uBlock Origin](https://github.com/gorhill/uBlock) and [Canvas Blocker](https://github.com/kkapsner/CanvasBlocker) (if that makes any difference).
(I hope I included any necessary information.)

![screenshot from 2018-11-17 02-06-37](https://user-images.githubusercontent.com/44369810/48658309-9a710880-ea37-11e8-9482-c35435e5a4c3.png)

**Comment by NullVoxPopuli** [comment]
Hi thanks for reporting!

Did you happen to whitelist https://mesh-relay-in-us-1.herokuapp.com/?

I need to add the mesh relay domains to the FAQ/troubleshooting page.

Hope this resolves the connection issue! And thank for providing so much detail about your setup!

**Comment by Phate6660** [comment]
I made sure to whitelist that as well. I just try to give as much info as I can, that way something can be figured out without having to go back and forth asking for more info. I mentioned the hardened user.js because I assumed maybe there is something required in the browser that was disabled by it.

Just found the issue. I completely forgot that I disabled websockets using [the chameleon extension.](https://addons.mozilla.org/en-US/firefox/addon/chameleon-ext/)

**Comment by NullVoxPopuli** [comment]
yup, there currently is no retry of message sending.
I think automatic message sending could lead to spamming a person, but I do have manual retrying of messages coming up ;)
hope this helps!
Also, glad you figured out what was causing the issue!

**Comment by Phate6660** [comment]
It's still not sending messages... I've checked the developer tools on Firefox and it seems like everything is loading in ok. I have a feeling that something got disabled (that's required) by the user.js and I'm going to have to slowly and tediously check each option in the user.js to see what's breaking it.

**Comment by NullVoxPopuli** [comment]
who are you trying to send messages to?
if you want to test with me, my invite link is : https://emberclear.io/invite?name=NullVoxPopuli&publicKey=bcd75a243e988bdfb9b19aaf1d3af2b7a02826a7a94c4ed2915481f825dddf62

**Comment by Phate6660** [comment]
Guess we can mark this as closed then.
