### ISSUE TITLE
Use `node-emojis` for emoji name replacement

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/emberclear#29]
https://github.com/tallesl/node-emojis
should this be live-swapped as you type? yes.
bundle size: https://bundlephobia.com/result?p=emojis@1.0.10 (small)

Add an option to disable

**Comment by tonowoe** [comment]
Yes! 😂

**Comment by NullVoxPopuli** [comment]
Resolved in #181
