### ISSUE TITLE
Implement a 2-factor-auth-esque technique for transferring content between devices

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/emberclear#30]
PreReq: https://github.com/NullVoxPopuli/emberclear/issues/58
Inspiration: https://gitlab.com/NullVoxPopuli/emberclear/issues/27

Plan:
 - Find State Machine Library
 - Design and implement Finite State Machine for the following Flow (which will cover the entirety of this feature)

The setup:
 - A user has a profile on a desktop computer (**desktop**)
 - they want to copy their profile to a new device (**mobile**)

The flow:
 - **desktop**: open settings
 - **desktop**: click "transfer to device"
    - QR Code appears containing only the public identity information 
      - QR Code generated should have the public identity information as well as an additional keypair for extra encryption of the profile code, in case some nefarious party sends a "Request profile info" message.
        - the "request profile info" message must be encrypted using the generate one-time-use keypair.
        - the User should still have to manually match up a code to prevent people with cameras nearby from also trying to capture the profile information

 - **mobile**: click login
 - **mobile**: click scan  
   - **mobile** scans the public identity information  
   - a temporary pub/priv key pair are generated on the **mobile** device  
   - the **mobile** device sends a specially formatted message to the **desktop**  
   - the **mobile** device displays a 6 digit Hex Code  
   - **desktop** opens a prompt containing the a hex code and asking to allow or deny the transfer and instructs the user that the hex codes on both devices must match before proceeding  
  - **desktop**: click allow  
    - desktop sends profile information in one message including contacts, channels, settings, etc to the mobile device over the p2p encrypted channel (the usual communication method)  
    - mobile receives the profile information and settings and imports it  
    - mobile logs the user in  
   
_The profile has successfully been transferred_

Thoughts:
 - to prevent spam requests for transferring profiles, maybe there should be a way to block people
   - this would help with bad-actors in general

**Comment by NullVoxPopuli** [comment]
Implementation Plan:
 - Find Finite State Machine Library
 - Design Finite State Machine for

**Comment by CelticMajora** [comment]
Note #110

**Comment by NullVoxPopuli** [comment]
Done in #733
However, that's just login.
Being able to sync when already lagged in on both devices would be good, too
