### ISSUE TITLE
Error handling after getUserMedia() initial denial

### ISSUE THREAD

**Issue by artemgurzhii** [NullVoxPopuli/emberclear#308]
**Steps to reproduce:**
1. open https://emberclear.io/add-friend and click `scan`
2. deny camera access
3. refresh the page and repeat steps 1 and 2

**Expected result:** Show warning that user need to give camera access

**P.S.** It also throws an error, probably [this code](https://github.com/NullVoxPopuli/emberclear/blob/7553ddcee96de6979d637def62bcfadf2320ffc9/packages/frontend/app/pods/components/q-r-scanner/component.ts#L30-L36) should be wrapped into `try/catch`

**Comment by NullVoxPopuli** [comment]
Wow, thanks for the debugging! This helps a ton!

**Comment by NullVoxPopuli** [comment]
PR for fix: https://github.com/NullVoxPopuli/emberclear/pull/309
