### ISSUE TITLE
Sub components under MU

### ISSUE THREAD

**Issue by SKMan** [NullVoxPopuli/emberclear#4]
Hi. Would very much like to know how you could achieve components under components, like;
chat-history -> message -> embedded-resource.

Have been trying this but I got "cannot find component".

Thanks.

**Comment by NullVoxPopuli** [comment]
how are you trying to invoke the component that results in "cannot find component"?
can you give an example component structure / templates?

**Comment by NullVoxPopuli** [comment]
is it:
```
src/ui/components/
- ok-form/
  component.js
  template.hbs // has <OkFormInput>input</OkFormInput>
  - ok-form-input/
    comporent.js
    template.hbs
```
?

**Comment by SKMan** [comment]
Exactly

**Comment by NullVoxPopuli** [comment]
what version of ember-source and ember-cli are you using?

**Comment by SKMan** [comment]
same as yours, copied from your package.json

**Comment by NullVoxPopuli** [comment]
how are you starting `ember s`?

**Comment by SKMan** [comment]
`EMBER_CLI_MODULE_UNIFICATION=true ember s`

**Comment by NullVoxPopuli** [comment]
what do you have in your environment.js?

**Comment by SKMan** [comment]
copied yours as well

**Comment by NullVoxPopuli** [comment]
what about optional-features.json?

**Comment by NullVoxPopuli** [comment]
also, if you clone this repo, does the project run?

**Comment by SKMan** [comment]
Same structure works in dummy app but when I add addon's components into dummy app, it cannot find. Sorry I should've mentioned that before.

**Comment by NullVoxPopuli** [comment]
yeah, I don't know if MU addons are ready for testing. could review in: https://github.com/emberjs/ember.js/issues/16373 to see what needs to be done to land support.

**Comment by SKMan** [comment]
Thank you so much. Sorry, took time.
