### ISSUE TITLE
Implement temporary processing for text commands in channels

### ISSUE THREAD

**Issue by amgassert** [NullVoxPopuli/emberclear#604]
This temporary module should parse commands from chat messages and invoke the corresponding methods provided by the module created for #605. This will be the predecessor to #607.

**Comment by GreenMobius** [comment]
The text parsing part is up and relatively easy to change if you want more or less commands. Any functionality is just waiting for the backend hookup.

**Comment by amgassert** [comment]
Closing in accordance with new plans
