### ISSUE TITLE
On small screens, the new channel form is not able to be hidden

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/emberclear#9]
See screenshot.
After clicking the + button (to the right of the channels header), the x button does not hide the form that appeared after clicking the + button

![screenshot_20181002-211909](https://user-images.githubusercontent.com/199018/46385249-2a761100-c689-11e8-9960-141df16c2267.png)

**Comment by sudonitesh** [comment]
I'd like to work on this

**Comment by sudonitesh** [comment]
@NullVoxPopuli when I tried it shows error
`[hitman@BlackBox emberclear (master *)]$ ./run yarn start:dev`
`./run: line 7: $'\r': command not found`
`./run: line 11: $'\r': command not found`
`./run: line 12: syntax error near unexpected token `$'{\r''`
`'/run: line 12: `function runstuff {`
[hitman@BlackBox emberclear (master *)]$`

**Comment by NullVoxPopuli** [comment]
@sudonitesh interesting, what OS are you on?

also, for this task, you can just work in the frontend directory, so:

```
cd packages/frontend
yarn && yarn start:dev
```
that should get you up and running :)

**Comment by sudonitesh** [comment]
I'm on ubuntu bash (WSL)

**Comment by NullVoxPopuli** [comment]
interesting. I'm on ubuntu, and use bash.
what's WSL?

not sure why the run script isn't compatible. hmm

**Comment by sudonitesh** [comment]
@NullVoxPopuli I thought I could get the Id of the "cross button" and use element selectors to hide the form. But I couldn't find the id's and where they are

**Comment by NullVoxPopuli** [comment]
I found this:
![image](https://user-images.githubusercontent.com/199018/46490204-60281080-c7d5-11e8-8166-806e2f41bbdb.png)

in `src/ui/components/sidebar/channels/template.hbs`

so, my hunch is that 
```hbs
  <a class='button is-small' {{action (mut isFormVisible) true}}>
```
needs to change to
```hbs
  <a class='button is-small' {{action (mut isFormVisible) (not isFormVisible)}}>
```
for a toggle-effect.

**Comment by NullVoxPopuli** [comment]
resolved by: https://gitlab.com/NullVoxPopuli/emberclear/commit/f69b7a106ade1f39f6c43a68bacc80bd755abf5f

![image](https://user-images.githubusercontent.com/199018/46862971-257d3400-cde4-11e8-8cf2-d16b4c51baa7.png)
